// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: karma.messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for updating karma
type KarmaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int32  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserId uint64 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *KarmaRequest) Reset() {
	*x = KarmaRequest{}
	mi := &file_karma_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KarmaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarmaRequest) ProtoMessage() {}

func (x *KarmaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karma_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarmaRequest.ProtoReflect.Descriptor instead.
func (*KarmaRequest) Descriptor() ([]byte, []int) {
	return file_karma_messages_proto_rawDescGZIP(), []int{0}
}

func (x *KarmaRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *KarmaRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *KarmaRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Response message for karma operations
type KarmaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *KarmaResponse) Reset() {
	*x = KarmaResponse{}
	mi := &file_karma_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KarmaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarmaResponse) ProtoMessage() {}

func (x *KarmaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karma_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarmaResponse.ProtoReflect.Descriptor instead.
func (*KarmaResponse) Descriptor() ([]byte, []int) {
	return file_karma_messages_proto_rawDescGZIP(), []int{1}
}

func (x *KarmaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_karma_messages_proto protoreflect.FileDescriptor

var file_karma_messages_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6b, 0x61, 0x72, 0x6d, 0x61, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a,
	0x0c, 0x4b, 0x61, 0x72, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x0d, 0x4b, 0x61, 0x72, 0x6d, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x36, 0x5a, 0x34, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x74, 0x69, 0x6e, 0x67,
	0x6f, 0x79, 0x61, 0x6c, 0x30, 0x39, 0x39, 0x36, 0x2f, 0x72, 0x65, 0x64, 0x64, 0x69, 0x74, 0x2d,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_karma_messages_proto_rawDescOnce sync.Once
	file_karma_messages_proto_rawDescData = file_karma_messages_proto_rawDesc
)

func file_karma_messages_proto_rawDescGZIP() []byte {
	file_karma_messages_proto_rawDescOnce.Do(func() {
		file_karma_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_karma_messages_proto_rawDescData)
	})
	return file_karma_messages_proto_rawDescData
}

var file_karma_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_karma_messages_proto_goTypes = []any{
	(*KarmaRequest)(nil),  // 0: proto.KarmaRequest
	(*KarmaResponse)(nil), // 1: proto.KarmaResponse
}
var file_karma_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_karma_messages_proto_init() }
func file_karma_messages_proto_init() {
	if File_karma_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_karma_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_karma_messages_proto_goTypes,
		DependencyIndexes: file_karma_messages_proto_depIdxs,
		MessageInfos:      file_karma_messages_proto_msgTypes,
	}.Build()
	File_karma_messages_proto = out.File
	file_karma_messages_proto_rawDesc = nil
	file_karma_messages_proto_goTypes = nil
	file_karma_messages_proto_depIdxs = nil
}
